// Collision flags

export const AMMO_BODYFLAG_STATIC_OBJECT = 1;
export const AMMO_BODYFLAG_KINEMATIC_OBJECT = 2;
export const AMMO_BODYFLAG_NORESPONSE_OBJECT = 4;
// Activation states

export const AMMO_BODYSTATE_ACTIVE_TAG = 1;
export const AMMO_BODYSTATE_ISLAND_SLEEPING = 2;
export const AMMO_BODYSTATE_WANTS_DEACTIVATION = 3;
export const AMMO_BODYSTATE_DISABLE_DEACTIVATION = 4;
export const AMMO_BODYSTATE_DISABLE_SIMULATION = 5;
